### ISSUE TITLE
Feature request: iterative AI-assisted development by creating pull requests

### ISSUE THREAD

**Issue by semikolon** [askthecode/askthecode.github.io#2]
Hi and thank you so much for this plugin. It's changing the way I work daily.

The only thing I'm missing now is the ability to integrate new code into my repositories.

I'm excited about the potential of closing the loop of copy-pasting new or updated code from the web chat when using GPT-4.

This plugin (or another one to complement it) (or a browser extension that works in unison) could create git diffs from suggested code changes, that could be used to create commits in the repo in a new branch and/or creating a Pull Request - after user approval (either file by file, or with the possibility of one-click approval for all suggested changes).

Then, after approval and possibly merging changes into the main branch, you'd come back to the chat and refresh the code from the repo before resuming further work. Rinse and repeat :D

This would probably require honing the prompts used to create diffs, to make sure they're accurate. It would also require this plugin to be able to annotate file content with line numbers, so that the diffs target the right lines of code.

I have a lot of time and energy to put into this right now, because of how I know it will speed up my workflow, if it could be made to work. Curious to hear your thoughts on this and how we could possibly collaborate. Send me an email if you like.

**Comment by dsomok** [comment]
Hi @semikolon,

thank you for your proposal! 
I'm glad to hear the plugin has been useful for you. I've sent a more detailed response to your email. Please check it out!
